package com.example.taskfour.alphabets;

public class AlphabetPhrases {
    public static final String[][] phrases = {
            {"willy’s real rear wheel","six sleek swans swam swiftly southwards","a happy hippo hopped and hiccupped","really leery, rarely Larry","fuzzy Wuzzy was a bear. fuzzy wuzzy had no hair. fuzzy wuzzy wasn’t very fuzzy, was he?","How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"blue bluebird","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"she sees cheese","six sticky skeletons","which witch is which?","a happy hippo hopped and hiccupped","cooks cook cupcakes quickly","How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"pad kid poured curd pulled cod","a happy hippo hopped and hiccupped","twelve twins twirled twelve twigs","blue bluebird","How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"short tongue twisters","eleven benevolent elephants","she sees cheese","six sticky skeletons","pad kid poured curd pulled cod","willy’s real rear wheel","six sleek swans swam swiftly southwards","scissors sizzle, thistles sizzle","a happy hippo hopped and hiccupped","really leery, rarely Larry","twelve twins twirled twelve twigs","blue bluebird","friendly fleas and fireflies","fresh fried fish","green glass globes glow greenly"},
            {"friendly fleas and fireflies","fresh fried fish","fuzzy Wuzzy was a bear. fuzzy wuzzy had no hair. fuzzy wuzzy wasn’t very fuzzy, was he?","How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood."},
            {"twelve twins twirled twelve twigs","green glass globes glow greenly"},
            {"she sees cheese","a happy hippo hopped and hiccupped","fresh fried fish","fuzzy Wuzzy was a bear. fuzzy wuzzy had no hair. fuzzy wuzzy wasn’t very fuzzy, was he?","How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"hort tongue twisters","six sticky skeletons","pad kid poured curd pulled cod","which witch is which?","six sleek swans swam swiftly southwards","scissors sizzle, thistles sizzle","a happy hippo hopped and hiccupped","twelve twins twirled twelve twigs","blue bluebird","friendly fleas and fireflies","fresh fried fish","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"cooks cook cupcakes quickly","How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"eleven benevolent elephants","six sticky skeletons","pad kid poured curd pulled cod","willy’s real rear wheel","six sleek swans swam swiftly southwards","scissors sizzle, thistles sizzle","really leery, rarely Larry","twelve twins twirled twelve twigs","blue bluebird","friendly fleas and fireflies","green glass globes glow greenly","How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"eleven benevolent elephants","a happy hippo hopped and hiccupped","green glass globes glow greenly","fuzzy Wuzzy was a bear. fuzzy wuzzy had no hair. fuzzy wuzzy wasn’t very fuzzy, was he?"},
            {"short tongue twisters","eleven benevolent elephants","pad kid poured curd pulled cod","scissors sizzle, thistles sizzle","a happy hippo hopped and hiccupped","green glass globes glow greenly","How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"eleven benevolent elephants","pad kid poured curd pulled cod","a happy hippo hopped and hiccupped","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"short tongue twisters","willy’s real rear wheel","really leery, rarely Larry","fresh fried fish","fuzzy Wuzzy was a bear. fuzzy wuzzy had no hair. fuzzy wuzzy wasn’t very fuzzy, was he?","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"short tongue twisters","she sees cheese","six sticky skeletons","which witch is which?","willy’s real rear wheel","six sleek swans swam swiftly southwards","scissors sizzle, thistles sizzle","cooks cook cupcakes quickly","twelve twins twirled twelve twigs","friendly fleas and fireflies","fresh fried fish","green glass globes glow greenly","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!","Six sick hicks nick six slick bricks with picks and sticks."},
            {"short tongue twisters","eleven benevolent elephants","six sticky skeletons","six sleek swans swam swiftly southwards","scissors sizzle, thistles sizzle","twelve twins twirled twelve twigs","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"short tongue twisters","pad kid poured curd pulled cod","cooks cook cupcakes quickly","blue bluebird","fuzzy Wuzzy was a bear. fuzzy wuzzy had no hair. fuzzy wuzzy wasn’t very fuzzy, was he?","How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"eleven benevolent elephants"},
            {"which witch is which?","willy’s real rear wheel","six sleek swans swam swiftly southwards","twelve twins twirled twelve twigs","fuzzy Wuzzy was a bear. fuzzy wuzzy had no hair. fuzzy wuzzy wasn’t very fuzzy, was he?","How much wood would a woodchuck chuck if a woodchuck could chuck wood? He would chuck, he would, as much as he could, and chuck as much wood as a woodchuck would if a woodchuck could chuck wood.","Yellow butter, purple jelly, red jam, black bread.Spread it thick, say it quick! Yellow butter, purple jelly, red jam, black bread.Spread it thicker, say it quicker! Yellow butter, purple jelly, red jam, black bread.Don’t eat with your mouth full!"},
            {"Six sick hicks nick six slick bricks with picks and sticks."},
            {"a happy hippo hopped and hiccupped","six sticky skeletons","cooks cook cupcakes quickly","really leery, rarely Larry","fuzzy Wuzzy was a bear. fuzzy wuzzy had no hair. fuzzy wuzzy wasn’t very fuzzy, was he?"},
            {"scissors sizzle, thistles sizzle","fuzzy Wuzzy was a bear. fuzzy wuzzy had no hair. fuzzy wuzzy wasn’t very fuzzy, was he?"}
    };
}
