package com.example.taskfour.GameObject;

public class GameImages {
    public static final String[] images = {
            "https://media-public.canva.com/i8S1U/MADk94i8S1U/2/tl.png","https://media-public.canva.com/MADKqs5anbU/1/thumbnail_large.png","https://media-public.canva.com/cS_p0/MADUixcS_p0/2/tl.png","https://media-public.canva.com/MADIKpEL-ds/1/thumbnail_large.png","https://media-public.canva.com/MADnBuRALlA/1/thumbnail_large.png",
            "https://media-public.canva.com/MABRSemdeb8/1/thumbnail.png","https://media-public.canva.com/Lh_BE/MADUhnLh_BE/2/tl.png","https://media-public.canva.com/MADKtdkv6_Q/1/thumbnail_large.png","https://media-public.canva.com/MADDImNF_pk/1/thumbnail_large.png","https://media-public.canva.com/EMfMI/MAD7ZoEMfMI/1/tl.png",
            "https://media-public.canva.com/kUods/MADsQ8kUods/1/thumbnail_large.png","https://media-public.canva.com/MADQDwJVQiM/1/thumbnail_large.png","https://media-public.canva.com/MADI2GRvED4/1/thumbnail_large.png","https://media-public.canva.com/MACUU8FD5G0/1/thumbnail_large.png","https://media-public.canva.com/MADpi7Htnao/2/thumbnail_large.png",
            "https://media-public.canva.com/MADpjT-Xfjw/2/thumbnail_large.png","https://media-public.canva.com/BxKQc/MADUiJBxKQc/2/tl.png","https://media-public.canva.com/MADBePTPp3Q/1/thumbnail_large.png","https://media-public.canva.com/MADit-8AEv8/1/thumbnail_large.png","https://media-public.canva.com/MACV8D4rBKY/1/thumbnail_large.png",
            "https://media-public.canva.com/MAB00KLZzRQ/1/thumbnail_large.png","https://media-public.canva.com/YqgPU/MADVmgYqgPU/2/tl.png","https://media-public.canva.com/MADGI4vMGNQ/1/thumbnail_large.png","https://media-public.canva.com/MACmyq2s3-w/1/thumbnail_large.png","https://media-public.canva.com/MAAuyTkGKyE/1/thumbnail.png",
            "https://media-public.canva.com/MADQD0mnYK0/1/thumbnail_large.png","https://media-public.canva.com/MAB0hx9nVfY/1/thumbnail_large.png","https://media-public.canva.com/MAC1gB0Tzuk/1/thumbnail_large.png","https://media-public.canva.com/MADHVVrgJfU/1/thumbnail_large.png","https://media-public.canva.com/MADrPJ1ISM0/1/thumbnail_large.png",
            "https://media-public.canva.com/ftBgw/MADfz3ftBgw/2/tl.png","https://media-public.canva.com/iaixk/MADmduiaixk/2/tl.png","https://media-public.canva.com/MACJvlypgFQ/1/thumbnail_large.png","https://media-public.canva.com/MADHSIfvVYQ/1/thumbnail_large.png","https://media-public.canva.com/0dp3A/MAD1aX0dp3A/1/tl.png",
            "https://media-public.canva.com/sm_Xc/MADsXysm_Xc/1/thumbnail_large.png","https://media-public.canva.com/MAAbfOlxJyM/1/thumbnail.png","https://media-public.canva.com/seJt0/MADytxseJt0/1/tl.png","https://media-public.canva.com/MACPWGR3v_k/1/thumbnail_large.png","https://media-public.canva.com/MACWcyZnaqE/1/thumbnail_large.png",
            "https://media-public.canva.com/lk820/MADsQ5lk820/1/thumbnail_large.png","https://media-public.canva.com/MAC2TdfGB0k/1/thumbnail_large.png","https://media-public.canva.com/cHlVw/MADSZacHlVw/2/tl.png","https://media-public.canva.com/MADitwQRMus/1/thumbnail_large.png","https://media-public.canva.com/XjOc0/MAD7ZgXjOc0/1/tl.png",
            "https://media-public.canva.com/MACy4T6heSI/5/thumbnail_large.png","https://media-public.canva.com/MACk1bWOVAU/1/thumbnail_large.png","https://media-public.canva.com/MADFklEpqMk/1/thumbnail_large.png","https://media-public.canva.com/f3mXE/MADUjNf3mXE/2/tl.png","https://media-public.canva.com/HFi7U/MADtBqHFi7U/1/thumbnail_large.png",
            "https://media-public.canva.com/gVudA/MADVnbgVudA/2/tl.png","https://media-public.canva.com/MADQD0uy-g0/1/thumbnail_large.png","https://media-public.canva.com/MKIpA/MADUhpMKIpA/2/tl.png","https://media-public.canva.com/MACLv0eWQlU/1/thumbnail_large.png","https://media-public.canva.com/KstKo/MADfz7KstKo/2/tl.png",
            "https://media-public.canva.com/hMSfk/MADY4fhMSfk/2/tl.png","https://media-public.canva.com/MADGuEFjUsw/1/thumbnail_large.png","https://media-public.canva.com/MpvFM/MADy0kMpvFM/1/tl.png","https://media-public.canva.com/MAC_LpysAz4/1/thumbnail_large.png","https://media-public.canva.com/Q7L20/MAD82-Q7L20/1/tl.png",
            "https://media-public.canva.com/MACBkwmKyhQ/1/thumbnail_large.png","https://media-public.canva.com/sa0Yk/MADgWZsa0Yk/2/tl.png","https://media-public.canva.com/MADDIzgk5uI/2/thumbnail_large.png","https://media-public.canva.com/MAB6mbI_9N8/1/thumbnail_large.png","https://media-public.canva.com/MADit9_cHS0/1/thumbnail_large.png",
            "https://media-public.canva.com/MACaOPrD3x0/1/thumbnail_large.png","https://media-public.canva.com/MACy4RRI2V8/5/thumbnail_large.png","https://media-public.canva.com/MADIKke-y0E/1/thumbnail_large.png","https://media-public.canva.com/Sj3bE/MAD2uGSj3bE/1/tl.png","https://media-public.canva.com/MADHVUr4OZc/1/thumbnail_large.png",
            "https://media-public.canva.com/MACBYcArkfM/1/thumbnail_large.png","https://media-public.canva.com/vWzFI/MADvwHvWzFI/1/tl.png","https://media-public.canva.com/MACy4S_7mgo/5/thumbnail_large.png","https://media-public.canva.com/MADEwLaxYdI/1/thumbnail_large.png","https://media-public.canva.com/r3dwA/MADUifr3dwA/2/tl.png",
            "https://media-public.canva.com/MACtQkmlg9s/1/thumbnail_large.png","https://media-public.canva.com/MADpjoHQQFs/1/thumbnail_large.png","https://media-public.canva.com/MACtQQHcmto/1/thumbnail_large.png","https://media-public.canva.com/jSbaA/MADSaEjSbaA/2/tl.png","https://media-public.canva.com/UPO8Q/MADVnWUPO8Q/2/tl.png",
            "https://media-public.canva.com/H2w-8/MAD1EXH2w-8/1/tl.png","https://media-public.canva.com/MADG8E-IfJw/1/thumbnail_large.png","https://media-public.canva.com/MADGY1twCc4/1/thumbnail_large.png","https://media-public.canva.com/oVYUM/MAD3pIoVYUM/1/tl.png", "https://media-public.canva.com/MACDm0GWscI/1/thumbnail_large.png",
            "https://media-public.canva.com/j-riY/MADhH8j-riY/3/tl.png","https://media-public.canva.com/MACy4VX1hdQ/5/thumbnail_large.png","https://media-public.canva.com/MACk1XO5vW8/1/thumbnail_large.png","https://media-public.canva.com/MACjqwVNLgA/1/thumbnail_large.png","https://media-public.canva.com/MADpjj5W4Js/1/thumbnail_large.png",
            "https://media-public.canva.com/MAB6vxizsU4/1/thumbnail_large.png","https://media-public.canva.com/MADQD5-dPEk/1/thumbnail_large.png","https://media-public.canva.com/MADit15w4Wc/1/thumbnail_large.png","https://media-public.canva.com/MADpjveHvUw/1/thumbnail_large.png","https://media-public.canva.com/3HN7w/MADuz23HN7w/1/tl.png",
            "https://media-public.canva.com/MADm768QukI/1/thumbnail_large.png","https://media-public.canva.com/MADQD3rbHXw/1/thumbnail_large.png","https://media-public.canva.com/MACF36Fcgv8/2/thumbnail_large.png","https://media-public.canva.com/OEoqg/MADT6UOEoqg/2/tl.png","https://media-public.canva.com/MACjnMzV9ps/1/thumbnail_large.png"
             };
}
